# Generated by Django 4.2.9 on 2024-03-18 21:56

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(
                    decimal_places=2,
                    max_digits=10
                )),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(
                    blank=True,
                    choices=[
                        ('Cleanser', 'cleanser'),
                        ('Moisturizer', 'moisturizer'),
                        ('Serum', 'serum'),
                        ('Sunscreen', 'sunscreen'),
                        ('Mask', 'mask'),
                        ('Toner', 'toner'),
                        ('Exfoliant', 'exfoliant'),
                        ('Eye Cream', 'eye_cream')
                    ],
                    max_length=20,
                    null=True
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_image', cloudinary.models.CloudinaryField(
                    default='placeholder',
                    max_length=255,
                    verbose_name='image'
                )),
                ('seller', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pages_products',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
